vectara_agentic/tools.py
Adding x-source-str to Vectara tool for internal tracking.
=> Add x-source-str to VectaraToolFactory

README.md, setup.py, tests/test_tools.py, vectara_agentic/__init__.py, vectara_agentic/agent.py, vectara_agentic/tools.py
LlamaIndex supports mutliple corpora already
Adding docs about this, and a new unit test
Also adjusted rerank_k to be no more than 100 in case of multiple corpora
=> Adding support for multiple corpora

requirements.txt, setup.py, vectara_agentic/__init__.py, vectara_agentic/_callback.py, vectara_agentic/_observability.py, vectara_agentic/_prompts.py, vectara_agentic/agent.py, vectara_agentic/tools.py, vectara_agentic/tools_catalog.py, vectara_agentic/types.py, vectara_agentic/utils.py
- Neo4j
- updated database tools to include sample_data tool
- Refactored guardrail tools
=> Added more tools

.flake8, vectara_agentic/_callback.py, vectara_agentic/_observability.py, vectara_agentic/agent.py, vectara_agentic/tools.py, vectara_agentic/tools_catalog.py
=> added .flake8 config file

.pylintrc, README.md, requirements-dev.txt, requirements.txt, setup.py, vectara_agentic/__init__.py, vectara_agentic/_prompts.py, vectara_agentic/db_tools.py, vectara_agentic/tools.py, vectara_agentic/tools_catalog.py
added slack tools
improved database tools and separated into db_tools.py minor updates to prompt
=> Improvements to DB tools

vectara_agentic/tools.py
Added new LlamaIndex capabilities (UDF and Chain Reranking) to the VectaraTool.
=> Add UDF and Chain Reranking

vectara_agentic/tools.py
fixed issue with x_source_str in llamaIndex
=> bugfix x_source_str

requirements.txt
This new version fixes the issue with chain reranking.
=> Bump Vectara Index Version

.pylintrc, README.md, requirements.txt, setup.py, vectara_agentic/__init__.py, vectara_agentic/_prompts.py, vectara_agentic/agent.py, vectara_agentic/db_tools.py, vectara_agentic/tools.py, vectara_agentic/types.py, vectara_agentic/utils.py
1. Now support arguments that can be used as conditional expressions. For example year can be "<2020" and it will build the filtering conditions properly
2. tool_args_types is a an optional dictionary providing annotations for arguments in tool_args_schema for "doc" or "part"
=> Improvements to create_rag_tool

vectara_agentic/tools.py
So that it works properly with LLMCompiler
=> Update to rag_function()

README.md, tests/test_agent.py, tests/test_tools.py, vectara_agentic/__init__.py, vectara_agentic/_observability.py, vectara_agentic/agent.py, vectara_agentic/agent_config.py, vectara_agentic/agent_endpoint.py, vectara_agentic/utils.py
So that you might be able to control config not only via env variables
=> Using AgentConfig

vectara_agentic/agent.py
If you include explicit instructions to use a tool that is undefined, it may result in a loop.
This adds tests to identify this case with an explicit message.
=> Fix issue with looping calls in agents

.pylintrc, requirements.txt, tests/test_agent.py, tests/test_serialization.py, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/db_tools.py, vectara_agentic/sub_query_workflow.py, vectara_agentic/tools.py, vectara_agentic/utils.py
Clean up items from 0.2.7
Fixed serialization issue with DB tools
Parallelization of summarization in search_tool
=> Cleanup, and bug fixes

vectara_agentic/_callback.py, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/agent_config.py, vectara_agentic/tools.py, vectara_agentic/utils.py
1. Fixed issue with AgentConfig
2. Added event_id in callback so that the user can map tool call with tool output
=> check agent/model type inconsistencies

vectara_agentic/sub_query_workflow.py
Tries to extract JSON component of LLM Response if LLM adds extra text to Workflow response.
=> Add protection for LLM Response

.github/workflows/publish_release.yml, tests/test_return_direct.py, tests/test_tools.py, tests/test_vectara_llms.py, vectara_agentic/_observability.py, vectara_agentic/_prompts.py, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/tool_utils.py, vectara_agentic/tools.py, vectara_agentic/tools_catalog.py
- Fixed PEP 625 issue
- Updated unit test
- Bug fixes in creating rag tools
=> version 0.2.15

docs/index.md, requirements.txt, vectara_agentic/_prompts.py, vectara_agentic/_version.py, vectara_agentic/llm_utils.py, vectara_agentic/tool_utils.py
fix for usage of anthropic
version bump
fix in exposing args properly in Tools
fixed prompt to address get_current_date issue
Upgraded version of llamaindex and llama-index-vectara
Default for OpenAI is now GPT-4.1
=> Various improvements

docs/index.md, tests/test_tools.py, vectara_agentic/_observability.py, vectara_agentic/_prompts.py, vectara_agentic/agent.py, vectara_agentic/llm_utils.py, vectara_agentic/tool_utils.py, vectara_agentic/tools_catalog.py
=> Fixed bug in range

README.md, docs/tools.md, requirements.txt, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/sub_query_workflow.py, vectara_agentic/tools.py
Handle "no sub-questions" gracefully
=> Upd workflows

requirements.txt, tests/test_api_endpoint.py, tests/test_tools.py, vectara_agentic/_version.py, vectara_agentic/agent_endpoint.py, vectara_agentic/llm_utils.py, vectara_agentic/tool_utils.py
- Remove monkey patch for openai_like since it's fixed now by llama-index (with upgrade of packages)
- Removed un-needed unit tests
- Updated api endpoint to have a "OpenAI-like API" and added unit tests
=> Openai like

docs/index.md, tests/test_agent_type.py, tests/test_groq.py, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/llm_utils.py
Moved default Google to Gemini-Flash-2.5
Some performance improvements
Added progress_callback and query_callback to serialization
=> Gemini 2.5 Flash as default for Gemini

requirements.txt, vectara_agentic/_prompts.py, vectara_agentic/_version.py, vectara_agentic/hhem.py, vectara_agentic/tools.py
=> Updated HHEM

requirements.txt, vectara_agentic/_prompts.py, vectara_agentic/_version.py, vectara_agentic/agent.py, vectara_agentic/llm_utils.py
Updates to prompt for better citation handling
Lazy loading of LLMs to improve startup time
=> New version 0.3.2
